# /home/rodrigo/.config/tmuxinator/dotfiles.yml

name: dotfiles
root: ~/programations/dotfiles-verdadeiro/

windows:
  - editor:
      root: ~/programations/dotfiles-verdadeiro/
      panes:
        - nvim .

  - term:
      root: ~/programations/dotfiles-verdadeiro/
      panes:
        - git status

