# /home/rodrigo/.config/tmuxinator/flowtify.yml

name: flowtify
root: ~/programations/granter/flowtify/

windows:
  - frontend-editor:
      root: ~/programations/granter/flowtify/frontend/flowtify-frontend
      panes:
        - nvim:
          - nix develop
          - nvim

  - backend-editor:
      root: ~/programations/granter/flowtify/backend/flowtify-backend
      panes:
        - nvim:
          - nix develop .#test
          - nvim

  - terminals:
      layout: tiled
      panes:
        - frontend-git:
          - cd ./frontend/flowtify-frontend
          - nix develop
          - git status
        - frontend-yarn: 
          - cd ./frontend/flowtify-frontend
          - nix develop
          - yarn dev --port 3001
        - backend-git:
          - cd ./backend/flowtify-backend
          - nix develop .#test
          - git status
        - backend-phx:
          - cd ./backend/flowtify-backend
          - nix develop
          - MIX_ENV=dev mix phx.server

  - granter-tools-editor:
      root: ~/programations/granter/flowtify/frontend/granter-tools
      panes:
        - nvim

  - granter-tools-term:
      root: ~/programations/granter/flowtify/frontend/granter-tools
      layout: even-horizontal
      panes:
        - yarn dev
        - git status

  - infra-editor:
      root: ~/programations/granter/flowtify/infra/
      panes:
        - nvim:
          - nix develop
          - nvim

  - infra-term:
      root: ~/programations/granter/flowtify/infra/
      layout: even-horizontal
      panes:
        - term:
          - nix develop
        - git:
          - nix develop
          - git status

