# /home/rodrigo/.config/tmuxinator/otter.yml

name: otter
root: ~/programations/granter/conecta_favu/otter

windows:
  - otter-frontend:
      root: ~/programations/granter/conecta_favu/otter/frontend/otter
      panes:
        - editor:
          - nix develop --command fish -c "nvim; fish"

  - otter-backend:
      root: ~/programations/granter/conecta_favu/otter/backend/otter
      panes:
        - editor:
          - nix develop .#test --command fish -c "nvim; fish"

  - terms:
      root: ~/programations/granter/conecta_favu/otter
      layout: main-vertical
      panes:
        - term:
          - git status

        - backend:
          - cd backend/otter
          - nix develop --command fish -c "MIX_ENV=dev mix phx.server; fish"

        - frontend: 
          - cd frontend/otter
          - nix develop --command fish -c "yarn dev; fish"
